### ISSUE TITLE
next and prev are undefined

### ISSUE THREAD

**Issue by FlynnHorrell** [FlynnHorrell/WebAppsLabs#70]

**Comment by FlynnHorrell** [comment]
console.log(this);
console.log(this.sentinel);

results in 
{ sentinel: { value: null, next: undefined, prev: undefined } }
{ value: null, next: undefined, prev: undefined }

Luke and I do not understand how next and prev are undefined.
Our function makeNewList is identical to yours.

@skiadas

**Comment by skiadas** [comment]
I sent a correction to everyone a few days ago, maybe you missed it. Let me see if I can find it.

Here it is

The list constructor contains the following:

sentinel = {
   value: null,
   next: sentinel,
   prev: sentinel
};

This will not work. It should instead be:

sentinel = { value: null };
sentinel.next = sentinel;
sentinel.prev = sentinel;

Haris Skiadas
Hanover College
